default: &default
  database: <%= "respira_#{Rails.env}" %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production_or_staging: &production_or_staging
  username: openicebergs
  password: <%= ENV['RESPIRA_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  <<: *production_or_staging
  
production:
  <<: *default
  <<: *production_or_staging
